name: DNS Sync on PR Merge

on:
  pull_request_target:
    types: [closed]
    paths:
      - 'whois/*.json'

# Global permissions
permissions: write-all

jobs:
  dns-sync:
    runs-on: ubuntu-latest
    name: DNS Synchronization
    
    # Only execute when PR is merged
    if: github.event.pull_request.merged == true
    
    steps:
    - name: Checkout main branch (for scripts and dependencies)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: .github/scripts
      run: |
        # Ensure package-lock.json is generated
        if [ ! -f "package-lock.json" ]; then
          npm install
        fi
        # Use ci for clean installation
        npm ci

    - name: Get PR information
      id: pr-info
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        script: |
          try {
            const prNumber = context.payload.pull_request.number;
            
            // Get PR information
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: parseInt(prNumber)
            });
            
            // Get file changes
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: parseInt(prNumber)
            });
            
            // Ensure all outputs have values
            core.setOutput('pr-title', pullRequest.title || '');
            core.setOutput('pr-body', pullRequest.body || '');
            core.setOutput('pr-number', prNumber.toString());
            core.setOutput('pr-author', pullRequest.user?.login || 'unknown');
            core.setOutput('files', JSON.stringify(files || []));
            core.setOutput('head-sha', pullRequest.head?.sha || '');
            core.setOutput('merge-sha', pullRequest.merge_commit_sha || '');
            
          } catch (error) {
            core.setFailed(`Failed to get PR information: ${error.message}`);
            // Set default values to prevent subsequent steps from failing
            core.setOutput('pr-title', '');
            core.setOutput('pr-body', '');
            core.setOutput('pr-number', '0');
            core.setOutput('pr-author', 'unknown');
            core.setOutput('files', '[]');
            core.setOutput('head-sha', '');
            core.setOutput('merge-sha', '');
          }

    - name: Debug PR Info
      if: always()
      run: |
        echo "PR Title: ${{ steps.pr-info.outputs.pr-title }}"
        echo "PR Number: ${{ steps.pr-info.outputs.pr-number }}"
        echo "PR Author: ${{ steps.pr-info.outputs.pr-author }}"
        echo "PR Files: ${{ steps.pr-info.outputs.files }}"
        echo "Merge SHA: ${{ steps.pr-info.outputs.merge-sha }}"

    # Checkout PR head to a separate directory for whois files
    - name: Checkout PR head (for whois files only)
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.pr-info.outputs.head-sha }}
        path: pr-files
        fetch-depth: 0
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    # Read whois file content from PR branch
    - name: Read whois file content
      id: read-whois
      run: |
        echo "Current working directory: $(pwd)"
        echo "Listing pr-files directory:"
        ls -la pr-files/ || echo "pr-files directory not found"
        
        FILES=$(echo '${{ steps.pr-info.outputs.files }}' | jq -r '.[] | select(.filename | startswith("whois/")) | .filename')
        echo "Found whois files: $FILES"
        
        for file in $FILES; do
          if [ -f "pr-files/$file" ]; then
            echo "Reading $file from PR branch"
            cat "pr-files/$file"
            # Copy to main workspace for script access
            cp "pr-files/$file" "$file"
            echo "Copied $file to main workspace"
            ls -la "$file"
          else
            echo "File $file not found in PR branch"
            echo "Available files in pr-files:"
            find pr-files/ -name "*.json" -type f 2>/dev/null || echo "No JSON files found"
          fi
        done
        
        echo "Final workspace structure:"
        ls -la whois/ || echo "whois directory not found"

    # Execute DNS sync script (using main branch scripts)
    - name: Execute DNS Sync
      id: dns-sync
      if: steps.pr-info.outputs.pr-title != ''
      working-directory: .github/scripts
      run: node dns-sync.js
      env:
        PR_TITLE: ${{ steps.pr-info.outputs.pr-title }}
        PR_FILES: ${{ steps.pr-info.outputs.files }}
        PDA_API_URL: ${{ secrets.PDA_API_URL }}
        PDA_API_KEY: ${{ secrets.PDA_API_KEY }}

    - name: Comment on PR
      if: always() && steps.pr-info.outputs.pr-title != ''
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          
          let syncResult;
          try {
            console.log('Reading DNS sync result file...');
            const resultData = fs.readFileSync('.github/scripts/dns-sync-result.json', 'utf8');
            console.log('DNS sync result file content:', resultData);
            syncResult = JSON.parse(resultData);
            console.log('Parsed DNS sync result:', JSON.stringify(syncResult, null, 2));
          } catch (error) {
            console.error('Error reading DNS sync result:', error);
            syncResult = {
              success: false,
              error: 'Failed to read DNS sync results',
              timestamp: new Date().toISOString()
            };
          }
          
          const prNumber = '${{ steps.pr-info.outputs.pr-number }}';
          const prTitle = '${{ steps.pr-info.outputs.pr-title }}';
          
          // Build comment content
          let commentBody = '';
          
          if (syncResult.success) {
            commentBody = `✅ **DNS Sync Successful**\n\n`;
            commentBody += `**Operation Type:** ${syncResult.operation}\n`;
            commentBody += `**Domain:** ${syncResult.domain}\n`;
            if (syncResult.nameservers) {
              commentBody += `**Nameservers:** ${syncResult.nameservers.join(', ')}\n`;
            }
            commentBody += `**Message:** ${syncResult.message}\n`;
            commentBody += `**Time:** ${new Date(syncResult.timestamp).toLocaleString('en-US')}\n`;
          } else {
            commentBody = `❌ **DNS Sync Failed**\n\n`;
            commentBody += `**Error:** ${syncResult.error}\n`;
            commentBody += `**Time:** ${new Date(syncResult.timestamp).toLocaleString('en-US')}\n`;
            commentBody += `\nPlease check PowerDNS Admin configuration and network connection.`;
          }
          
          // Find existing DNS sync comments
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: parseInt(prNumber)
          });
          
          const dnsSyncComments = comments.filter(comment => 
            comment.user.login === 'github-actions[bot]' && 
            (comment.body.includes('DNS Sync Successful') || comment.body.includes('DNS Sync Failed'))
          );
          
          // Delete old DNS sync comments
          for (const comment of dnsSyncComments) {
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: comment.id
            });
          }
          
          // Add new comment
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: parseInt(prNumber),
            body: commentBody
          });

    - name: Create commit status
      if: always() && steps.pr-info.outputs.merge-sha != ''
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          
          let syncResult;
          try {
            const resultData = fs.readFileSync('.github/scripts/dns-sync-result.json', 'utf8');
            syncResult = JSON.parse(resultData);
          } catch (error) {
            syncResult = {
              success: false,
              error: 'Failed to read DNS sync results'
            };
          }
          
          const mergeSha = '${{ steps.pr-info.outputs.merge-sha }}';
          const prTitle = '${{ steps.pr-info.outputs.pr-title }}';
          
          const state = syncResult.success ? 'success' : 'failure';
          const description = syncResult.success 
            ? `DNS Sync Successful: ${syncResult.message}`
            : `DNS Sync Failed: ${syncResult.error}`;
          
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: mergeSha,
            state: state,
            description: description.substring(0, 140),
            context: 'DNS Sync'
          }); 