name: validate-pr

on:
  # 自动触发
  pull_request_target:  # 改用 pull_request_target 以获得正确的token权限
    types: [opened, synchronize, reopened, edited]
    paths:
      - 'whois/*.json'
  # 手动触发
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to validate'
        required: true
        type: string
      force_validation:
        description: 'Force validation even if PR is closed'
        required: false
        type: boolean
        default: false

# 全局权限设置
permissions: write-all

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    name: Validate Pull Request
    
    steps:
    - name: Checkout base repository
      uses: actions/checkout@v4
      with:
        path: base
        fetch-depth: 0
        ref: main
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Checkout PR
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v4
      with:
        path: pr
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Copy validation scripts
      run: |
        mkdir -p pr/.github/scripts
        cp -r base/.github/scripts/* pr/.github/scripts/
        rm -rf base

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: pr/.github/scripts
      run: |
        # 确保生成 package-lock.json
        if [ ! -f "package-lock.json" ]; then
          npm install
        fi
        # 使用 ci 进行清洁安装
        npm ci

    - name: Get PR information
      id: pr-info
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        script: |
          try {
            let prNumber;
            // 根据触发方式获取 PR 号
            if ('${{ github.event_name }}' === 'workflow_dispatch') {
              prNumber = '${{ github.event.inputs.pr_number }}';
              const forceValidation = '${{ github.event.inputs.force_validation }}' === 'true';
              
              const { data: pullRequest } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: parseInt(prNumber)
              });
              
              if (pullRequest.state === 'closed' && !forceValidation) {
                core.setFailed(`PR #${prNumber} is closed. Use force_validation to validate anyway.`);
                return;
              }
            } else {
              prNumber = context.payload.pull_request.number;
            }
            
            // 获取PR信息
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: parseInt(prNumber)
            });
            
            // 获取文件变更
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: parseInt(prNumber)
            });
            
            // 确保所有输出都有值
            core.setOutput('pr-title', pullRequest.title || '');
            core.setOutput('pr-body', pullRequest.body || '');
            core.setOutput('pr-number', prNumber.toString());
            core.setOutput('pr-author', pullRequest.user?.login || 'unknown');
            core.setOutput('files', JSON.stringify(files || []));
            core.setOutput('head-sha', pullRequest.head?.sha || '');
            core.setOutput('pr-state', pullRequest.state || 'unknown');
            core.setOutput('pr-repo', pullRequest.head?.repo?.full_name || context.repo.full_name);
            
          } catch (error) {
            core.setFailed(`Failed to get PR information: ${error.message}`);
            // 设置默认值以防止后续步骤出错
            core.setOutput('pr-title', '');
            core.setOutput('pr-body', '');
            core.setOutput('pr-number', '0');
            core.setOutput('pr-author', 'unknown');
            core.setOutput('files', '[]');
            core.setOutput('head-sha', '');
            core.setOutput('pr-state', 'unknown');
            core.setOutput('pr-repo', context.repo.full_name);
          }

    - name: Debug PR Info
      if: always()
      run: |
        echo "PR Title: ${{ steps.pr-info.outputs.pr-title }}"
        echo "PR Body: ${{ steps.pr-info.outputs.pr-body }}"
        echo "PR Number: ${{ steps.pr-info.outputs.pr-number }}"
        echo "PR Author: ${{ steps.pr-info.outputs.pr-author }}"
        echo "PR Files: ${{ steps.pr-info.outputs.files }}"
        echo "Head SHA: ${{ steps.pr-info.outputs.head-sha }}"
        echo "PR State: ${{ steps.pr-info.outputs.pr-state }}"
        echo "PR Repository: ${{ steps.pr-info.outputs.pr-repo }}"

    - name: Validate Pull Request
      id: validate
      if: steps.pr-info.outputs.pr-title != ''
      working-directory: pr/.github/scripts
      run: node validate-pr.js
      env:
        PR_TITLE: ${{ steps.pr-info.outputs.pr-title }}
        PR_BODY: ${{ steps.pr-info.outputs.pr-body }}
        PR_NUMBER: ${{ steps.pr-info.outputs.pr-number }}
        PR_AUTHOR: ${{ steps.pr-info.outputs.pr-author }}
        PR_FILES: ${{ steps.pr-info.outputs.files }}
        HEAD_SHA: ${{ steps.pr-info.outputs.head-sha }}
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ steps.pr-info.outputs.pr-repo }}

    - name: Comment on PR
      if: always() && steps.pr-info.outputs.pr-title != ''
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          
          let validationResult;
          try {
            const resultData = fs.readFileSync('pr/.github/scripts/validation-result.json', 'utf8');
            validationResult = JSON.parse(resultData);
          } catch (error) {
            validationResult = {
              isValid: false,
              errors: ['Failed to read validation results'],
              report: '❌ PR Validation Failed\n\nInternal error occurred during validation.'
            };
          }
          
          const prNumber = '${{ steps.pr-info.outputs.pr-number }}';
          
          // Find existing validation comments
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: parseInt(prNumber)
          });
          
          const validationComments = comments.filter(comment => 
            comment.user.login === 'github-actions[bot]' && 
            (comment.body.includes('PR Validation Passed') || 
             comment.body.includes('PR Validation Failed'))
          );
          
          const commentBody = validationResult.report + 
            '\n\n---\n' + 
            ('${{ github.event_name }}' === 'workflow_dispatch' 
              ? '*This validation was triggered manually by @${{ github.actor }}*' 
              : '*This validation was triggered automatically*') +
            '\n\n*Validation Time: ' + new Date().toISOString() + '*';
          
          // Delete all existing validation comments except the most recent one
          if (validationComments.length > 0) {
            // Sort comments by creation time, newest first
            validationComments.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
            
            // Update the most recent comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: validationComments[0].id,
              body: commentBody
            });
            
            // Delete any other validation comments
            for (let i = 1; i < validationComments.length; i++) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: validationComments[i].id
              });
            }
          } else {
            // Create new comment if no existing validation comments found
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt(prNumber),
              body: commentBody
            });
          }

    - name: Update check status
      if: always() && steps.pr-info.outputs.pr-title != ''
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          let conclusion = 'failure';
          let summary = 'Validation failed';
          
          try {
            const resultData = fs.readFileSync('pr/.github/scripts/validation-result.json', 'utf8');
            const validationResult = JSON.parse(resultData);
            
            if (validationResult.isValid) {
              conclusion = 'success';
              summary = 'All validation checks passed';
            } else {
              summary = 'Validation failed: ' + validationResult.errors.join(', ');
            }
          } catch (error) {
            summary = 'Failed to read validation results: ' + error.message;
          }
          
          await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'validate-pr',
            head_sha: '${{ steps.pr-info.outputs.head-sha }}',
            status: 'completed',
            conclusion: conclusion,
            output: {
              title: 'PR Validation',
              summary: summary
            }
          });

    - name: Check validation result
      if: always() && steps.pr-info.outputs.pr-title != ''
      run: |
        if [ -f pr/.github/scripts/validation-result.json ]; then
          VALIDATION_RESULT=$(cat pr/.github/scripts/validation-result.json)
          IS_VALID=$(echo "$VALIDATION_RESULT" | jq -r '.isValid')
          if [ "$IS_VALID" != "true" ]; then
            echo "PR validation failed"
            exit 1
          fi
        else
          echo "Validation result file not found"
          exit 1
        fi 